# Generated by Django 5.2.8 on 2026-01-28 16:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0014_trainingcycle_unique_user_weekly_cycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlitzTacticsSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('puzzles', models.JSONField(help_text='Lista de IDs de puzzles seleccionados (30 puzzles)')),
                ('current_puzzle_index', models.PositiveIntegerField(default=0)),
                ('time_remaining', models.PositiveIntegerField(default=180, help_text='Tiempo restante en segundos')),
                ('failures', models.PositiveIntegerField(default=0, help_text='Número de fallos acumulados (máximo 3)')),
                ('completed', models.BooleanField(default=False)),
                ('score', models.PositiveIntegerField(default=0, help_text='Cantidad de puzzles resueltos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blitz_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlitzTacticsAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle_id', models.CharField(max_length=100)),
                ('solved', models.BooleanField()),
                ('time_taken', models.PositiveIntegerField(blank=True, help_text='Tiempo empleado en segundos', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='chess.blitztacticssession')),
            ],
        ),
        migrations.AddIndex(
            model_name='blitztacticssession',
            index=models.Index(fields=['user', 'date'], name='chess_blitz_user_id_2ca6a3_idx'),
        ),
        migrations.AddConstraint(
            model_name='blitztacticssession',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_user_daily_blitz_session'),
        ),
        migrations.AddIndex(
            model_name='blitztacticsattempt',
            index=models.Index(fields=['session', 'created_at'], name='chess_blitz_session_226762_idx'),
        ),
    ]
