# Generated by Django 5.2.8 on 2026-02-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0016_visionrushsession_visionrushattempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visionrushattempt',
            name='memorization_time',
            field=models.FloatField(blank=True, help_text='Tiempo de memorización en segundos', null=True),
        ),
        migrations.AddField(
            model_name='visionrushattempt',
            name='response_time',
            field=models.FloatField(blank=True, help_text='Tiempo de respuesta en segundos', null=True),
        ),
    ]
