# Generated by Django 5.2.8 on 2026-01-28 16:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0013_alter_trainingcycle_total_puzzles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='trainingcycle',
            constraint=models.UniqueConstraint(fields=('user', 'start_date'), name='unique_user_weekly_cycle'),
        ),
    ]
