# Generated by Django 5.2.8 on 2026-02-01 16:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0015_blitztacticssession_blitztacticsattempt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisionRushSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('exercises', models.JSONField(help_text='Lista de ejercicios seleccionados (15 ejercicios)')),
                ('current_exercise_index', models.PositiveIntegerField(default=0)),
                ('failures', models.PositiveIntegerField(default=0, help_text='Número de fallos acumulados')),
                ('completed', models.BooleanField(default=False)),
                ('score', models.PositiveIntegerField(default=0, help_text='Cantidad de ejercicios resueltos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vision_rush_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VisionRushAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_data', models.JSONField(help_text='Datos del ejercicio (fen, pregunta, respuesta correcta)')),
                ('user_answer', models.CharField(help_text='Respuesta proporcionada por el usuario', max_length=100)),
                ('solved', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='chess.visionrushsession')),
            ],
        ),
        migrations.AddIndex(
            model_name='visionrushsession',
            index=models.Index(fields=['user', 'date'], name='chess_visio_user_id_b14ee6_idx'),
        ),
        migrations.AddConstraint(
            model_name='visionrushsession',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_user_daily_vision_rush_session'),
        ),
        migrations.AddIndex(
            model_name='visionrushattempt',
            index=models.Index(fields=['session', 'created_at'], name='chess_visio_session_0546d6_idx'),
        ),
    ]
