# Generated by Django 5.2.8 on 2026-02-18 13:58

import django.db.models.deletion
from django.db import migrations, models


def create_categories_from_parents(apps, schema_editor):
    Theme = apps.get_model('chess', 'Theme')
    ThemeCategory = apps.get_model('chess', 'ThemeCategory')
    
    # Crear categorías a partir de Themes con parent=None (categorías existentes)
    categories = Theme.objects.filter(parent=None, is_trainable=False)
    for theme in categories:
        category, created = ThemeCategory.objects.get_or_create(
            name=theme.name,
            defaults={
                'lichess_name': theme.lichess_name,
                'description': theme.description,
            }
        )
        # Asignar categoría a todos los temas que tenían este theme como parent
        Theme.objects.filter(parent=theme).update(category=category)
    
    # También hay temas con parent=None pero is_trainable=True? No debería según validación.
    # Si existen, los tratamos como temas sin categoría (category null)


def assign_category_from_parent(apps, schema_editor):
    # Esta función es redundante porque ya asignamos en la anterior, pero por seguridad
    Theme = apps.get_model('chess', 'Theme')
    ThemeCategory = apps.get_model('chess', 'ThemeCategory')
    
    # Para cada tema con parent no nulo, asignar categoría si aún no tiene
    for theme in Theme.objects.filter(parent__isnull=False).select_related('parent'):
        if theme.parent:
            # Buscar categoría correspondiente al parent
            category = ThemeCategory.objects.filter(name=theme.parent.name).first()
            if category:
                theme.category = category
                theme.save()


def reverse_migration(apps, schema_editor):
    Theme = apps.get_model('chess', 'Theme')
    ThemeCategory = apps.get_model('chess', 'ThemeCategory')
    
    # Revertir: crear Themes como categorías a partir de ThemeCategory
    for category in ThemeCategory.objects.all():
        theme, created = Theme.objects.get_or_create(
            name=category.name,
            defaults={
                'lichess_name': category.lichess_name,
                'description': category.description,
                'is_trainable': False,
                'parent': None,
            }
        )
        # Asignar parent a los temas que tienen esta categoría
        Theme.objects.filter(category=category).update(parent=theme)
    
    # Eliminar categorías? No es necesario porque se eliminará el modelo en reversa.


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0017_visionrushattempt_memorization_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('lichess_name', models.CharField(blank=True, help_text='Nombre de la categoría en Lichess (opening/middlegame/endgame/mate)', max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Descripción de la categoría')),
            ],
            options={
                'verbose_name_plural': 'Theme categories',
                'ordering': ['name'],
            },
        ),
        # Agregar campo category temporalmente null
        migrations.AddField(
            model_name='theme',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Categoría a la que pertenece el tema', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='chess.themecategory'),
        ),
        # Migrar datos
        migrations.RunPython(create_categories_from_parents, reverse_migration),
        # Eliminar campo parent después de migración
        migrations.RemoveField(
            model_name='theme',
            name='parent',
        ),
    ]
