# Generated by Django 5.2.8 on 2026-05-13 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chess", "0019_remove_theme_is_trainable_alter_theme_category_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="blitztacticssession",
            name="unique_user_daily_blitz_session",
        ),
        migrations.RemoveConstraint(
            model_name="visionrushsession",
            name="unique_user_daily_vision_rush_session",
        ),
    ]
