# Generated by Django 6.0 on 2026-07-20 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chess", "0021_add_document_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FreeActiveExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puzzle_id", models.CharField(max_length=100)),
                (
                    "theme_lichess_name",
                    models.CharField(
                        help_text="Tema elegido (lichess_name) para obtener nuevos puzzles",
                        max_length=100,
                    ),
                ),
                ("rating_min", models.PositiveIntegerField()),
                ("rating_max", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="free_active_exercise",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
