# Generated by Django 6.0 on 2026-07-28 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chess", "0023_elosnapshot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainingcycletheme",
            name="priority",
        ),
    ]
