# Generated by Django 6.0 on 2026-07-31 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chess", "0024_remove_trainingcycletheme_priority"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FreePuzzleAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puzzle_id", models.CharField(max_length=100)),
                ("solved", models.BooleanField()),
                (
                    "theme_lichess_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Tema seleccionado al momento del intento",
                        max_length=100,
                    ),
                ),
                (
                    "rating_min",
                    models.PositiveIntegerField(
                        help_text="Rating mínimo del rango de dificultad"
                    ),
                ),
                (
                    "rating_max",
                    models.PositiveIntegerField(
                        help_text="Rating máximo del rango de dificultad"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="free_puzzle_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="chess_freep_user_id_b71649_idx",
                    ),
                    models.Index(
                        fields=["puzzle_id"], name="chess_freep_puzzle__2a83ba_idx"
                    ),
                ],
            },
        ),
    ]
