# Generated by Django 6.0 on 2026-08-01 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chess", "0025_freepuzzleattempt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingPlanConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Activar para usar configuración personalizada en lugar de los defaults",
                    ),
                ),
                ("puzzles_per_cycle", models.PositiveIntegerField(default=100)),
                ("themes_per_cycle", models.PositiveIntegerField(default=10)),
                (
                    "theme_selection_mode",
                    models.CharField(
                        choices=[
                            ("weakest", "Más débiles"),
                            ("custom", "Personalizado"),
                        ],
                        default="weakest",
                        help_text="Modo de selección de temas para el ciclo",
                        max_length=20,
                    ),
                ),
                (
                    "blitz_puzzles",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Cantidad de puzzles por sesión de Blitz Tactics",
                    ),
                ),
                (
                    "vision_exercises",
                    models.PositiveIntegerField(
                        default=15,
                        help_text="Cantidad de ejercicios por sesión de Vision Rush",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "selected_themes",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Temas seleccionados (solo usado en modo Personalizado)",
                        to="chess.theme",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_plan_config",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
