# Generated by Django 6.0 on 2026-08-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chess", "0026_add_training_plan_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingplanconfig",
            name="blitz_sessions_per_cycle",
            field=models.PositiveIntegerField(
                default=5, help_text="Sesiones esperadas de Blitz Tactics por ciclo"
            ),
        ),
        migrations.AddField(
            model_name="trainingplanconfig",
            name="vision_sessions_per_cycle",
            field=models.PositiveIntegerField(
                default=5, help_text="Sesiones esperadas de Vision Rush por ciclo"
            ),
        ),
    ]
