# Generated by Django 6.0 on 2026-08-01 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chess", "0027_add_sessions_per_cycle"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="puzzleattempt",
            name="elo_change",
            field=models.IntegerField(
                blank=True,
                help_text="Cambio de Elo general tras este intento",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="puzzleattempt",
            name="is_retry",
            field=models.BooleanField(
                default=False, help_text="Si fue un puzzle reintentado"
            ),
        ),
        migrations.AddField(
            model_name="puzzleattempt",
            name="mode",
            field=models.CharField(
                choices=[("cycle", "Ciclo"), ("blitz", "Blitz")],
                default="cycle",
                help_text="Modo de entrenamiento en que se realizó",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="puzzleattempt",
            name="puzzle_rating",
            field=models.PositiveIntegerField(
                blank=True, help_text="Rating Lichess del puzzle", null=True
            ),
        ),
        migrations.AddField(
            model_name="puzzleattempt",
            name="theme",
            field=models.ForeignKey(
                blank=True,
                help_text="Tema del puzzle",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="chess.theme",
            ),
        ),
        migrations.AddIndex(
            model_name="puzzleattempt",
            index=models.Index(
                fields=["user", "mode", "created_at"],
                name="chess_puzzl_user_id_3ac731_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="puzzleattempt",
            index=models.Index(
                fields=["user", "theme", "created_at"],
                name="chess_puzzl_user_id_ebf87d_idx",
            ),
        ),
    ]
