# Generated by Django 5.2.8 on 2026-08-03 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chess", "0028_add_puzzle_attempt_rich_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainingpreferences",
            name="user",
        ),
        migrations.RemoveIndex(
            model_name="themeelo",
            name="chess_theme_user_id_8e0b8c_idx",
        ),
        migrations.RemoveIndex(
            model_name="themeelo",
            name="chess_theme_theme_i_9d2f1a_idx",
        ),
        migrations.DeleteModel(
            name="TrainingPreferences",
        ),
    ]
